app:
  name: "Account Microservice - Update"
  version: "v1"
  level: "Production"

server:
  port: 8081
  servlet:
    context-path: /api/v1
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId}]"
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:7373/eureka
    
spring:
  datasource:
    url: jdbc:mysql://accounts-db:3306/accounts-db
    username: root
    password: password
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


info:
  app:
    name: "Account Microservice"
    description: "Account Microservice"
    version: "1.0"
      
