app:
  name: "Account Microservice - Update"
  version: "v1"
  level: "Production"

server:
  port: 8081
  servlet:
    context-path: /api/v1
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7373/eureka
    
spring:
  datasource:
    url: jdbc:mysql://accounts-db:3306/accounts-db
    username: root
    password: password
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

info:
  app:
    name: "Account Microservice"
    description: "Account Microservice"
    version: "1.0"
      
