app:
  name: "Account Microservice - Update"
  version: "v1"
  level: "Production"

server:
  port: 8081
  servlet:
    context-path: /api/v1
    
spring:
  datasource:
    url: jdbc:mysql://accounts-db:3306/accounts-db
    username: root
    password: password
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
