
app:
  name: "Card Microservice - Update"
  version: "v1"
  level: "Production"

server:
  port: 9090
  servlet:
    context-path: /api/v1

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:7373/eureka
    
spring:
  datasource:
    url: jdbc:mysql://cards-db:3306/cards-db
    username: root
    password: password
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "%5p [%X{spring.application.name},%X{traceId},%X{spanId}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info: 
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

endpoint:
  shutdown:
    enabled: true
