
app:
  name: "Loans Microservice"
  version: "v1"
  level: "Production"

server:
  port: 9090
  servlet:
    context-path: /api/v1
    
spring:
  datasource:
    url: jdbc:mysql://loans-db:3306/loans-db
    username: root
    password: password
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

